### PR TITLE
Terminate the qtconsoles on IDA termination.

### LINKED ISSUE #13: Terminate IPython on IDA termination
I think the IPython console should terminate when IDA terminates. Or at least get some sort of notification.

The issue I keep running into is that I open multiple instances of IDA, and multiple instances of the qtconsole. All the consoles have the same title, and there is no indication when I close IDA. So I have multiple shells, and I have to actually type in code to see which one are still active :sob: 

The possible solutions I can think of are:
1. If IDA spawns the qtconsole, it should also terminate it (easy, just save process information and kill it). This is kinda safe, as you can't really attach the console to multiple instances.
2. Somehow indicate to Jupyter that the kernel has died.
3. Set the title of the qtconsole window to match the IDA window.

The first seams the easiest.

### PR DESCRIPTION
**Pull request by james91b**
@tmr232 

Resolves #13, ready to be tested and reviewed.

### CODE REVIEW

**Comment by tmr232** [comment]
Works great for me.

The only thing I am unsure about is whether we should use the `atexit` or the plugin's `term` callback.

**Comment by james91b** [comment]
I thought about that. However, i think that given that plugin should only terminate when IDA exits and i think we should try keep as much as we can in python for simplicity reasons. I went with atexit.

**Comment by tmr232** [comment]
Seems like a great argument for the `atexit` solution.

**Comment by tmr232** [comment]
Been messing with the code a bit to add the menu, and came up with a new idea.
Why not add a Python callback for `init`, `run` and `term`, so that we can do whatever we like?

I am suggesting this as terminators are needed for menus as well. Again - we can say it doesn't matter. But I think the code would end up looking far cleaner.

**Comment by james91b** [comment]
I agree that makes sense if we are going to use it for other things. I'll change this to use a callback.

**Comment by james91b** [comment]
@tmr232 Adding a termination callback is actually more complicated than i thought. Unfortunately, the python plugin is being terminated before the termination of ida_ipython. So python has already been terminated, and we have no way to call the function. Unless we can somehow guarantee the termination order of the plugins to call ida_ipython termination first, i can't see a simple way of doing this.

**Comment by tmr232** [comment]
@james91b I think we will have to make do. Probably better to gather all code into one registered `atexit` callback, isn't it?

**Pull request merged**
